const state={activeTarget:null,rows:[],gls:null,fit:null,mode:"Demo Target",source:"Synthetic demonstration dataset"};
const COLORS=["#26f0ff","#39ff7f","#ffd15c","#b59cff","#ff667c","#80ffd0"];
const TARGETS=[
{key:"51 peg",planet:"51 Pegasi b",host:"51 Peg",aliases:["51 peg","51 pegasi","51 pegasi b","hd 217014"],type:"Star + hot Jupiter",ra:"22:57:27.98",dec:"+20:46:07.8",spt:"G2IV",vmag:"5.49",distance:"15.6 pc",parallax:"64.1 mas",period:4.2308,k:55.9,ecc:.013,mass:"0.46 MJ",semiMajor:"0.052 AU",omega:78,note:"Canonical hot-Jupiter system used here as a demonstration target."},
{key:"hd 189733",planet:"HD 189733 b",host:"HD 189733",aliases:["hd 189733","hd189733","hd 189733 b"],type:"Star + transiting hot Jupiter",ra:"20:00:43.71",dec:"+22:42:39.1",spt:"K1V",vmag:"7.67",distance:"19.8 pc",parallax:"50.6 mas",period:2.2186,k:205.0,ecc:.004,mass:"1.13 MJ",semiMajor:"0.031 AU",omega:90,note:"Bright transiting hot-Jupiter system useful for RV plus photometry workflows."},
{key:"proxima cen",planet:"Proxima Centauri b",host:"Proxima Cen",aliases:["proxima","proxima cen","proxima centauri","proxima b","proxima centauri b"],type:"M dwarf + terrestrial candidate",ra:"14:29:42.95",dec:"-62:40:46.1",spt:"M5.5V",vmag:"11.13",distance:"1.30 pc",parallax:"768.5 mas",period:11.186,k:1.4,ecc:.08,mass:"≥1.1 M⊕",semiMajor:"0.049 AU",omega:110,note:"Low-amplitude nearby M-dwarf RV system; useful for demonstrating activity caution."},
{key:"barnard",planet:"Barnard RV Candidate",host:"Barnard's Star",aliases:["barnard","barnards star","barnard's star"],type:"M dwarf RV target",ra:"17:57:48.50",dec:"+04:41:36.2",spt:"M4V",vmag:"9.54",distance:"1.83 pc",parallax:"547.5 mas",period:3.154,k:.5,ecc:.05,mass:"sub-Earth scale",semiMajor:"compact orbit",omega:70,note:"Illustrative low-amplitude RV target for cm/s-scale workflow design."}
];
const plotBase={paper_bgcolor:"transparent",plot_bgcolor:"transparent",font:{family:"Inter, system-ui, sans-serif",color:"#7f9aa7",size:10},margin:{l:55,r:18,t:26,b:44},xaxis:{gridcolor:"rgba(117,238,255,0.055)",linecolor:"rgba(117,238,255,0.18)",tickcolor:"rgba(117,238,255,0.22)",zerolinecolor:"rgba(117,238,255,0.12)",ticks:"inside",showline:true},yaxis:{gridcolor:"rgba(117,238,255,0.055)",linecolor:"rgba(117,238,255,0.18)",tickcolor:"rgba(117,238,255,0.22)",zerolinecolor:"rgba(117,238,255,0.12)",ticks:"inside",showline:true}};
function layout(extra={}){const o={...plotBase,...extra};if(extra.xaxis)o.xaxis={...plotBase.xaxis,...extra.xaxis};if(extra.yaxis)o.yaxis={...plotBase.yaxis,...extra.yaxis};return o}
function fmt(v,d=3){return Number.isFinite(Number(v))?Number(v).toFixed(d):"—"}function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}function std(a){const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}function rms(a){return Math.sqrt(mean(a.map(x=>x*x)))}function safeSet(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function setUTCClock(){safeSet("utcClock",new Date().toISOString().slice(11,19))}
function splitCSVLine(line){const out=[];let cur="",q=false;for(const ch of line){if(ch==='"')q=!q;else if((ch===","||ch==="\t"||ch===";")&&!q){out.push(cur.trim().replace(/^"|"$/g,""));cur=""}else cur+=ch}out.push(cur.trim().replace(/^"|"$/g,""));return out}
function parseRV(text){const lines=text.trim().split(/\r?\n/).filter(l=>l.trim()&&!l.trim().startsWith("#"));if(lines.length<3)throw Error("Need a header and at least two data rows.");const h=splitCSVLine(lines[0]).map(x=>x.toLowerCase().replace(/["']/g,"").trim());const find=a=>{for(const n of a){const i=h.indexOf(n);if(i>=0)return i}return-1};const it=find(["bjd","time","jd","hjd","bjd_tdb","mjd"]),ir=find(["rv","vrad","radvel","velocity","mnvel"]),ie=find(["rv_err","rverr","err","error","e_rv","e_vrad","sigma"]),ii=find(["instrument","inst","telescope","facility"]),ib=find(["bis","bis_span","bisspan"]),iw=find(["fwhm","fwhm_ccf"]);if(it<0||ir<0)throw Error("Missing required BJD/Time or RV column.");const rows=[];for(let n=1;n<lines.length;n++){const c=splitCSVLine(lines[n]),t=parseFloat(c[it]),rv=parseFloat(c[ir]);if(!Number.isFinite(t)||!Number.isFinite(rv))continue;rows.push({t,rv,err:ie>=0?Math.max(parseFloat(c[ie])||1,.001):1,inst:ii>=0?(c[ii]||"UNKNOWN").trim():"UNKNOWN",bis:ib>=0?parseFloat(c[ib]):NaN,fwhm:iw>=0?parseFloat(c[iw]):NaN})}rows.sort((a,b)=>a.t-b.t);if(rows.length<3)throw Error("Fewer than 3 valid RV rows after parsing.");return rows}
function solveKepler(M,e){let E=e<.8?M:Math.PI;for(let i=0;i<30;i++){const d=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));E-=d;if(Math.abs(d)<1e-12)break}return E}
function trueAnomaly(E,e){return 2*Math.atan2(Math.sqrt(1+e)*Math.sin(E/2),Math.sqrt(1-e)*Math.cos(E/2))}
function keplerianRV(t,p){const M=((2*Math.PI/p.P)*(((t-p.T0)%p.P)+p.P))%(2*Math.PI);const E=solveKepler(M,p.e);const nu=trueAnomaly(E,p.e);return p.K*(Math.cos(p.w+nu)+p.e*Math.cos(p.w))}
function instrumentOffsets(rows,p){const inst=[...new Set(rows.map(r=>r.inst))],g={};for(const x of inst){let sw=0,sv=0;for(const r of rows.filter(q=>q.inst===x)){const w=1/(r.err*r.err),m=p?keplerianRV(r.t,p):0;sw+=w;sv+=w*(r.rv-m)}g[x]=sw?sv/sw:0}const ref=g[inst[0]]||0;for(const x of inst)g[x]-=ref;return g}
function residuals(rows,p){const g=p.gammas||instrumentOffsets(rows,p);return rows.map(r=>r.rv-(g[r.inst]||0)-keplerianRV(r.t,p))}
function computeGLS(rows,nf=1200){const t=rows.map(r=>r.t),y=rows.map(r=>r.rv),e=rows.map(r=>r.err),N=t.length,span=t[N-1]-t[0];const fmin=Math.max(1e-6,2/span),fmax=Math.min(2,(N/(2*span))*10),w=e.map(x=>1/(x*x)),W=w.reduce((a,b)=>a+b,0);let ybar=0;for(let i=0;i<N;i++)ybar+=w[i]*y[i];ybar/=W;let YY=0;for(let i=0;i<N;i++)YY+=w[i]*(y[i]-ybar)**2;YY/=W||1;const periods=[],powers=[];let bestZ=-1,bestP=null;for(let k=0;k<nf;k++){const f=fmin*Math.pow(fmax/fmin,k/(nf-1)),om=2*Math.PI*f;let C=0,S=0,YC=0,YS=0,CC=0,SS=0,CS=0;for(let i=0;i<N;i++){const wi=w[i]/W,dy=y[i]-ybar,co=Math.cos(om*t[i]),si=Math.sin(om*t[i]);C+=wi*co;S+=wi*si;YC+=wi*dy*co;YS+=wi*dy*si;CC+=wi*co*co;SS+=wi*si*si;CS+=wi*co*si}CC-=C*C;SS-=S*S;CS-=C*S;const D=CC*SS-CS*CS;let power=0;if(Math.abs(D)>1e-24)power=Math.max(0,Math.min(1,(SS*YC*YC+CC*YS*YS-2*CS*YC*YS)/(YY*D)));const P=1/f;periods.push(P);powers.push(power);if(power>bestZ){bestZ=power;bestP=P}}return{periods,powers,bestP,bestZ,N,M:nf}}
function fapLevel(fap,N,M){return Math.max(0,Math.min(.999,1-Math.pow(fap/M,2/(N-3))))}
function fitAtPeriod(rows,P){const rvs=rows.map(r=>r.rv),K0=(Math.max(...rvs)-Math.min(...rvs))/2,eIn=parseFloat(document.getElementById("eccInput").value),wIn=parseFloat(document.getElementById("omegaInput").value);const eGrid=[...new Set([0,.02,.05,.1,.2,.35,.5,Number.isFinite(eIn)?eIn:0])].filter(e=>e>=0&&e<.9),wGrid=Array.from({length:18},(_,i)=>i*20*Math.PI/180);if(Number.isFinite(wIn))wGrid.push(wIn*Math.PI/180);const kGrid=[.55,.75,1,1.25,1.55].map(x=>x*K0),t0Grid=Array.from({length:32},(_,i)=>rows[0].t+i*P/32);let best={chi2:Infinity,P,K:K0,e:0,w:0,T0:rows[0].t,gammas:{}};for(const e of eGrid)for(const w of wGrid)for(const K of kGrid)for(const T0 of t0Grid){const p={P,K,e,w,T0},g=instrumentOffsets(rows,p);let chi2=0;for(const r of rows){const q=r.rv-(g[r.inst]||0)-keplerianRV(r.t,p);chi2+=q*q/(r.err*r.err)}if(chi2<best.chi2)best={P,K,e,w,T0,chi2,gammas:g}}best.residuals=residuals(rows,best);best.rms=rms(best.residuals);return best}
function byInstrumentTrace(rows,yFn,xFn){const inst=[...new Set(rows.map(r=>r.inst))];return inst.map((x,i)=>{const s=rows.filter(r=>r.inst===x);return{x:s.map(xFn),y:s.map(yFn),mode:"markers",name:x,marker:{color:COLORS[i%COLORS.length],size:6,line:{color:"#02070d",width:1}},error_y:{type:"data",array:s.map(r=>r.err),visible:true,color:COLORS[i%COLORS.length]+"80",thickness:1,width:3}}})}
function pearson(xs,ys){const valid=[];for(let i=0;i<xs.length;i++)if(Number.isFinite(xs[i])&&Number.isFinite(ys[i]))valid.push([xs[i],ys[i]]);if(valid.length<3)return NaN;const x=valid.map(v=>v[0]),y=valid.map(v=>v[1]),mx=mean(x),my=mean(y);let cov=0,sx=0,sy=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;cov+=dx*dy;sx+=dx*dx;sy+=dy*dy}return cov/Math.sqrt(sx*sy)}
function findTarget(q){const query=q.toLowerCase().trim();return TARGETS.find(t=>t.aliases.some(a=>a.includes(query)||query.includes(a)))||TARGETS[0]}
function setTarget(t){state.activeTarget=t;safeSet("targetName",t.planet);safeSet("hostName",t.host);safeSet("targetRA",t.ra);safeSet("targetDec",t.dec);safeSet("targetSpT",t.spt);safeSet("targetDist",t.distance);safeSet("targetK",`${t.k} m/s`);safeSet("dashPlanet",t.planet);safeSet("dashPeriod",`${t.period} d`);safeSet("dashMass",t.mass);safeSet("dashEcc",String(t.ecc));safeSet("idMain",t.host);safeSet("idType",t.type);safeSet("idRA",t.ra);safeSet("idDec",t.dec);safeSet("idVmag",t.vmag);safeSet("idDistance",t.distance);safeSet("idParallax",t.parallax);safeSet("idSpT",t.spt);document.getElementById("periodInput").value=t.period;document.getElementById("kInput").value=t.k;document.getElementById("eccInput").value=t.ecc;document.getElementById("omegaInput").value=t.omega;renderPlanetTable(t);drawSkyCanvas(t);renderArchiveGrid(t);loadSyntheticDemo(t,false);renderReport()}
function renderTargetList(){document.getElementById("targetList").innerHTML=TARGETS.map(t=>`<button data-target="${t.key}"><strong>${t.planet}</strong><small>${t.host} · ${t.spt} · ${t.distance}</small></button>`).join("");document.querySelectorAll("#targetList button").forEach(b=>b.addEventListener("click",()=>setTarget(TARGETS.find(t=>t.key===b.dataset.target))))}
function renderPlanetTable(t){const rows=[["Planet",t.planet],["Host",t.host],["Period",`${t.period} d`],["K semi-amplitude",`${t.k} m/s`],["Eccentricity",t.ecc],["m sin i",t.mass],["Semi-major axis",t.semiMajor],["Note",t.note]];document.getElementById("planetTable").innerHTML=rows.map(r=>`<div><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join("")}
function drawSkyCanvas(t){const c=document.getElementById("skyCanvas");if(!c)return;const ctx=c.getContext("2d"),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle="#02070d";ctx.fillRect(0,0,w,h);let seed=0;for(let i=0;i<(t.host+t.ra+t.dec).length;i++)seed+=(t.host+t.ra+t.dec).charCodeAt(i)*(i+1);const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let i=0;i<155;i++){const x=rand()*w,y=rand()*h,r=.5+rand()*1.8,a=.3+rand()*.7;ctx.beginPath();ctx.fillStyle=`rgba(210,245,255,${a})`;ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}const cx=w*.52,cy=h*.48;ctx.strokeStyle="rgba(38,240,255,.35)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx,0);ctx.lineTo(cx,h);ctx.moveTo(0,cy);ctx.lineTo(w,cy);ctx.stroke();ctx.strokeStyle="rgba(38,240,255,.8)";for(const R of[22,45,70]){ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.fillStyle="#fff";ctx.shadowColor="#26f0ff";ctx.shadowBlur=18;ctx.arc(cx,cy,4.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#26f0ff";ctx.font="12px JetBrains Mono";ctx.fillText(t.host,16,24);ctx.fillStyle="#7f9aa7";ctx.fillText(`RA ${t.ra}`,16,h-34);ctx.fillText(`DEC ${t.dec}`,16,h-16)}
function generateSyntheticRows(t){let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296},gauss=()=>Math.sqrt(-2*Math.log(rand()+1e-10))*Math.cos(2*Math.PI*rand());const p={P:t.period,K:t.k,e:t.ecc,w:t.omega*Math.PI/180,T0:2451500};const rows=[],blocks=[{t:2451500,n:38,inst:"HARPS",gamma:0},{t:2451880,n:24,inst:"HIRES",gamma:t.k*.08},{t:2452520,n:28,inst:"ESPRESSO",gamma:-t.k*.04}],noise=Math.max(.75,Math.min(3.2,t.k*.035));for(const b of blocks)for(let i=0;i<b.n;i++){const time=b.t+rand()*170;rows.push({t:time,rv:keplerianRV(time,p)+b.gamma+gauss()*noise,err:.6+rand()*1.2,inst:b.inst,bis:gauss()*(t.k*.18),fwhm:7200+gauss()*65})}rows.sort((a,b)=>a.t-b.t);return rows}
function setData(rows,source,mode){state.rows=rows;state.source=source;state.mode=mode;state.gls=null;state.fit=null;safeSet("systemMode",mode);safeSet("rvSourceLabel",mode==="Uploaded RV Data"?"UPLOADED":"DEMO");updateFitSummary();renderAllPlots();renderActivitySummary();renderReport()}
function loadSyntheticDemo(t=state.activeTarget||TARGETS[0]){const rows=generateSyntheticRows(t);setData(rows,`Synthetic ${t.planet} demonstration`, "Demo Target");state.gls=computeGLS(rows);state.fit=fitAtPeriod(rows,t.period);renderAllPlots();updateFitSummary();renderActivitySummary();renderReport()}
function updateFitSummary(){const rows=state.rows||[],bestP=state.gls?`${fmt(state.gls.bestP,6)} d`:"—",res=state.fit?`${fmt(state.fit.rms,2)} m/s`:"—";document.getElementById("fitSummary").innerHTML=`<div><span>Rows</span><strong>${rows.length||"—"}</strong></div><div><span>Best period</span><strong>${bestP}</strong></div><div><span>RMS residual</span><strong>${res}</strong></div>`}
function renderAllPlots(){renderRVPlot("rvPlot");renderRVPlot("labRVPlot");renderPhasePlot("phasePlot");renderPhasePlot("labPhasePlot");renderResidualPlot("residualPlot");renderResidualPlot("labResidualPlot");renderActivityPlot("activityPlot");state.gls?(renderPeriodogram("periodogramPlot"),renderPeriodogram("labGLSPlot")):(renderEmptyPeriodogram("periodogramPlot"),renderEmptyPeriodogram("labGLSPlot"))}
function renderRVPlot(id){const rows=state.rows;if(!rows.length)return;const traces=byInstrumentTrace(rows,r=>state.fit?r.rv-(state.fit.gammas[r.inst]||0):r.rv,r=>r.t);if(state.fit){const t0=rows[0].t,t1=rows.at(-1).t,tt=Array.from({length:800},(_,i)=>t0+i*(t1-t0)/799);traces.push({x:tt,y:tt.map(t=>keplerianRV(t,state.fit)),mode:"lines",name:"Keplerian fit",line:{color:"#fff",width:2}})}Plotly.react(id,traces,layout({title:"Radial-velocity time series",xaxis:{title:"BJD"},yaxis:{title:state.fit?"RV − γ (m/s)":"RV (m/s)"},showlegend:true,legend:{orientation:"h",x:0,y:1.15}}),{responsive:true,displayModeBar:false})}
function renderEmptyPeriodogram(id){Plotly.react(id,[],layout({title:"Run period scan to generate periodogram",xaxis:{title:"Period (days)"},yaxis:{title:"Power"}}),{responsive:true,displayModeBar:false})}
function renderPeriodogram(id){const g=state.gls;if(!g)return renderEmptyPeriodogram(id);const ymax=Math.max(...g.powers,fapLevel(.001,g.N,g.M)*1.08);const traces=[{x:g.periods,y:g.powers,mode:"lines",name:"Power",line:{color:"#26f0ff",width:2}}];[[.1,"FAP 10%","#7f9aa7"],[.01,"FAP 1%","#ffd15c"],[.001,"FAP 0.1%","#ff667c"]].forEach(r=>traces.push({x:[g.periods[0],g.periods.at(-1)],y:[fapLevel(r[0],g.N,g.M),fapLevel(r[0],g.N,g.M)],mode:"lines",name:r[1],line:{color:r[2],dash:"dash",width:1}}));traces.push({x:[g.bestP,g.bestP],y:[0,ymax],mode:"lines",name:`Best P = ${fmt(g.bestP,5)} d`,line:{color:"#b59cff",dash:"dot",width:1.5}});Plotly.react(id,traces,layout({title:"Generalized Lomb–Scargle periodogram",xaxis:{title:"Period (days)",type:"log"},yaxis:{title:"Power",range:[0,ymax*1.06]},showlegend:true}),{responsive:true,displayModeBar:false})}
function renderPhasePlot(id){const rows=state.rows;if(!rows.length)return;const P=state.fit?state.fit.P:state.gls?state.gls.bestP:parseFloat(document.getElementById("periodInput").value),T0=state.fit?state.fit.T0:rows[0].t;const traces=byInstrumentTrace(rows,r=>state.fit?r.rv-(state.fit.gammas[r.inst]||0):r.rv,r=>(((r.t-T0)%P)+P)%P/P);if(state.fit){const ph=Array.from({length:500},(_,i)=>i/499);traces.push({x:ph,y:ph.map(p=>keplerianRV(T0+p*P,state.fit)),mode:"lines",name:"Fit",line:{color:"#fff",width:2}})}Plotly.react(id,traces,layout({title:"Phase-folded RV curve",xaxis:{title:"Orbital phase"},yaxis:{title:state.fit?"RV − γ (m/s)":"RV (m/s)"},showlegend:true}),{responsive:true,displayModeBar:false})}
function renderResidualPlot(id){if(!state.fit){Plotly.react(id,[],layout({title:"Residuals appear after Keplerian fit",xaxis:{title:"BJD"},yaxis:{title:"O − C (m/s)"}}),{responsive:true,displayModeBar:false});return}const rows=state.rows,rv=state.fit.residuals,inst=[...new Set(rows.map(r=>r.inst))],tr=[{x:[rows[0].t,rows.at(-1).t],y:[0,0],mode:"lines",name:"zero",line:{color:"rgba(255,255,255,.28)",dash:"dot"}}];inst.forEach((x,i)=>{const p=rows.map((r,j)=>[r,rv[j]]).filter(q=>q[0].inst===x);tr.push({x:p.map(q=>q[0].t),y:p.map(q=>q[1]),mode:"markers",name:x,marker:{color:COLORS[i%COLORS.length],size:6}})});Plotly.react(id,tr,layout({title:"Observed − computed residuals",xaxis:{title:"BJD"},yaxis:{title:"O − C (m/s)"},showlegend:true}),{responsive:true,displayModeBar:false})}
function renderActivityPlot(id){const rows=state.rows,key=rows.some(r=>Number.isFinite(r.bis))?"bis":rows.some(r=>Number.isFinite(r.fwhm))?"fwhm":null;if(!key){Plotly.react(id,[],layout({title:"Upload BIS/FWHM to activate diagnostic",xaxis:{title:"Activity indicator"},yaxis:{title:"RV (m/s)"}}),{responsive:true,displayModeBar:false});return}const traces=byInstrumentTrace(rows,r=>r.rv,r=>r[key]),rVal=pearson(rows.map(r=>r[key]),rows.map(r=>r.rv));if(Number.isFinite(rVal))traces.push({x:[NaN],y:[NaN],mode:"markers",name:`Pearson r = ${fmt(rVal,3)}`,marker:{color:"#ffd15c"}});Plotly.react(id,traces,layout({title:`RV versus ${key.toUpperCase()}`,xaxis:{title:key.toUpperCase()},yaxis:{title:"RV (m/s)"},showlegend:true}),{responsive:true,displayModeBar:false})}
function renderActivitySummary(){const rows=state.rows,key=rows.some(r=>Number.isFinite(r.bis))?"bis":rows.some(r=>Number.isFinite(r.fwhm))?"fwhm":null;if(!key){safeSet("jitterScore","UNKNOWN");safeSet("jitterText","Upload BIS or FWHM columns to estimate activity correlation.");return}const r=Math.abs(pearson(rows.map(x=>x[key]),rows.map(x=>x.rv)));if(!Number.isFinite(r)){safeSet("jitterScore","UNKNOWN");safeSet("jitterText","Not enough valid activity points.");return}if(r<.25){safeSet("jitterScore","LOW");safeSet("jitterText",`Weak RV–${key.toUpperCase()} correlation in the current dataset.`);safeSet("triageFlag","NOMINAL")}else if(r<.55){safeSet("jitterScore","MEDIUM");safeSet("jitterText",`Moderate RV–${key.toUpperCase()} correlation. Interpret the periodogram with caution.`);safeSet("triageFlag","WATCH")}else{safeSet("jitterScore","HIGH");safeSet("jitterText",`Strong RV–${key.toUpperCase()} correlation. Signal may be activity-contaminated.`);safeSet("triageFlag","ACTIVITY")}}
function renderArchiveGrid(t){const q=encodeURIComponent(t.host),planet=encodeURIComponent(t.planet);const cards=[["NASA/IPAC","Exoplanet Archive",`https://exoplanetarchive.ipac.caltech.edu/overview/${planet}`,"Planet parameters, system overview and archive context."],["DACE","Exoplanet portal","https://dace.unige.ch/exoplanets/","RV-focused portal for public exoplanet systems and analysis workflows."],["CDS","SIMBAD",`https://simbad.cds.unistra.fr/simbad/sim-id?Ident=${q}`,"Object identity, coordinates, references and cross-identifications."],["STScI","MAST","https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html","Kepler, K2 and TESS photometric context."],["ESA","Gaia Archive","https://gea.esac.esa.int/archive/","Astrometry, parallax and proper-motion context."],["CDS","VizieR",`https://vizier.cds.unistra.fr/viz-bin/VizieR?-source=&-c=${q}`,"Published catalogue tables and literature measurements."]];document.getElementById("archiveGrid").innerHTML=cards.map(c=>`<a class="archive-card" href="${c[2]}" target="_blank"><span>${c[0]}</span><strong>${c[1]}</strong><p>${c[3]}</p></a>`).join("")}
function renderSJDEMatrix(){const m=document.getElementById("sjdeMatrix");let h="";for(let i=0;i<240;i++){const hot=i%17===0||i%29===0,cold=i%11===0||i%7===0;h+=`<span class="matrix-cell ${hot?"hot":cold?"cold":""}"></span>`}m.innerHTML=h}
function renderReport(){const t=state.activeTarget||TARGETS[0],rows=state.rows||[];const lines=[];lines.push("JANA DOPPLER OBSERVATORY — SESSION REPORT");lines.push("==========================================");lines.push("");lines.push(`Target planet:      ${t.planet}`);lines.push(`Host star:          ${t.host}`);lines.push(`Object type:        ${t.type}`);lines.push(`Coordinates:        RA ${t.ra}, Dec ${t.dec}`);lines.push(`Spectral type:      ${t.spt}`);lines.push(`Distance:           ${t.distance}`);lines.push(`Parallax:           ${t.parallax}`);lines.push("");lines.push("PLANET CONTEXT");lines.push("------------------------------------------");lines.push(`Period:             ${t.period} d`);lines.push(`RV semi-amplitude:  ${t.k} m/s`);lines.push(`Eccentricity:       ${t.ecc}`);lines.push(`m sin i:            ${t.mass}`);lines.push(`Semi-major axis:    ${t.semiMajor}`);lines.push("");lines.push("CURRENT DATASET");lines.push("------------------------------------------");lines.push(`Mode:               ${state.mode}`);lines.push(`Source:             ${state.source}`);lines.push(`Rows:               ${rows.length}`);lines.push(`Instruments:        ${rows.length?[...new Set(rows.map(r=>r.inst))].join(", "):"—"}`);lines.push(`Best period scan:   ${state.gls?fmt(state.gls.bestP,6)+" d":"not computed"}`);lines.push(`Fit RMS residual:   ${state.fit?fmt(state.fit.rms,3)+" m/s":"not fitted"}`);lines.push("");lines.push("NEXT ANALYSIS STEPS");lines.push("------------------------------------------");lines.push("1. Check periodogram aliases and sampling window.");lines.push("2. Compare RV signal with BIS/FWHM/activity channels.");lines.push("3. Inspect residuals after the first-pass Keplerian model.");lines.push("4. Cross-check target context through NASA Archive, SIMBAD, Gaia and MAST.");document.getElementById("reportText").textContent=lines.join("\n")}
function loadFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const rows=parseRV(r.result);setData(rows,`User-uploaded RV data: ${file.name}`,"Uploaded RV Data");state.gls=computeGLS(rows);document.getElementById("periodInput").value=state.gls.bestP.toFixed(6);renderAllPlots();updateFitSummary();renderReport()}catch(e){alert("Parse error: "+e.message)}};r.readAsText(file)}
function switchTab(id){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===id));setTimeout(()=>{renderAllPlots();drawSkyCanvas(state.activeTarget||TARGETS[0])},80)}
function bindEvents(){document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>switchTab(b.dataset.tab)));document.getElementById("targetSearchBtn").addEventListener("click",()=>setTarget(findTarget(document.getElementById("targetSearch").value)));document.getElementById("targetSearch").addEventListener("keydown",e=>{if(e.key==="Enter")setTarget(findTarget(e.target.value))});document.getElementById("fileInput").addEventListener("change",e=>loadFile(e.target.files[0]));const dz=document.getElementById("dropZone");dz.addEventListener("click",()=>document.getElementById("fileInput").click());dz.addEventListener("dragover",e=>{e.preventDefault();dz.classList.add("drag")});dz.addEventListener("dragleave",()=>dz.classList.remove("drag"));dz.addEventListener("drop",e=>{e.preventDefault();dz.classList.remove("drag");loadFile(e.dataTransfer.files[0])});document.getElementById("demoBtn").addEventListener("click",()=>loadSyntheticDemo(state.activeTarget||TARGETS[0]));document.getElementById("runPeriodogramBtn").addEventListener("click",()=>{if(!state.rows.length)return;state.gls=computeGLS(state.rows);document.getElementById("periodInput").value=state.gls.bestP.toFixed(6);renderAllPlots();updateFitSummary();renderReport()});document.getElementById("fitBtn").addEventListener("click",()=>{if(!state.rows.length)return;const P=parseFloat(document.getElementById("periodInput").value);if(!Number.isFinite(P)||P<=0){alert("Enter a valid period before fitting.");return}state.fit=fitAtPeriod(state.rows,P);renderAllPlots();updateFitSummary();renderActivitySummary();renderReport()});document.getElementById("refreshReportBtn").addEventListener("click",renderReport);document.getElementById("copyReportBtn").addEventListener("click",async()=>{await navigator.clipboard.writeText(document.getElementById("reportText").textContent);alert("Report copied to clipboard.")})}
function init(){setUTCClock();setInterval(setUTCClock,1000);renderTargetList();renderSJDEMatrix();bindEvents();setTarget(TARGETS[0]);switchTab("dashboard")}init();
